/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Accounts {
  accessToken: string | null;
  accessTokenExpiresAt: number | null;
  accountId: string;
  createdAt: number;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: number | null;
  scope: string | null;
  updatedAt: number;
  userId: string;
}

export interface Sessions {
  createdAt: number;
  expiresAt: number;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: number;
  userAgent: string | null;
  userId: string;
}

export interface Users {
  createdAt: number;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  updatedAt: number;
}

export interface Verification {
  createdAt: number;
  expiresAt: number;
  id: string;
  identifier: string;
  updatedAt: number;
  value: string;
}

export interface DB {
  accounts: Accounts;
  sessions: Sessions;
  users: Users;
  verification: Verification;
}
