/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as MainRouteImport } from "./routes/_main"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as MainIndexRouteImport } from "./routes/_main/index"
import { Route as ApiPingRouteImport } from "./routes/api/ping"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$"

const MainRoute = MainRouteImport.update({
  id: "/_main",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MainRoute,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: "/api/ping",
  path: "/api/ping",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/login": typeof AuthLoginRoute
  "/api/ping": typeof ApiPingRoute
  "/": typeof MainIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  "/login": typeof AuthLoginRoute
  "/api/ping": typeof ApiPingRoute
  "/": typeof MainIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_auth": typeof AuthRouteWithChildren
  "/_main": typeof MainRouteWithChildren
  "/_auth/login": typeof AuthLoginRoute
  "/api/ping": typeof ApiPingRoute
  "/_main/": typeof MainIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/login" | "/api/ping" | "/" | "/api/auth/$"
  fileRoutesByTo: FileRoutesByTo
  to: "/login" | "/api/ping" | "/" | "/api/auth/$"
  id:
    | "__root__"
    | "/_auth"
    | "/_main"
    | "/_auth/login"
    | "/api/ping"
    | "/_main/"
    | "/api/auth/$"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  ApiPingRoute: typeof ApiPingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_main": {
      id: "/_main"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_main/": {
      id: "/_main/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    "/api/ping": {
      id: "/api/ping"
      path: "/api/ping"
      fullPath: "/api/ping"
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/api/auth/$": {
      id: "/api/auth/$"
      path: "/api/auth/$"
      fullPath: "/api/auth/$"
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  ApiPingRoute: ApiPingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
